#' Read results of batch CFM prediction
#'
#' @param out_dir A path to a directory containing text files generated by
#'   \code{cfm_predict_batch}
#' @param table_name A name to be used for the resultant database table
#' @param output_path A path to a SQLite database file for writing the results
#'
#' @return
#' @export
#'
cfm_read_batch <-
  function(out_dir = NULL,
           table_name = NULL,
           output_path = NULL) {
    stopifnot(exprs = {
      !is.null(out_dir)
      !is.null(table_name)
      !is.null(output_path)
    })
    tmp <-
      dplyr::tibble(filename = fs::dir_ls(out_dir, glob = '*.txt')) %>%
      dplyr::mutate(ID = gsub(".txt", "", x = basename(filename))) %>%
      dplyr::rowwise(.) %>%
      dplyr::mutate(spectrum = blob::as_blob(readBin(filename, 'raw', 1e6))) %>%
      dplyr::ungroup(.)
    if (!is.null(output_path)) {
      conn <- DBI::dbConnect(RSQLite::SQLite(), output_path)
      on.exit(DBI::dbDisconnect(conn))
      DBI::dbWriteTable(conn, table_name, tmp)
    } else{
      return(tmp)
    }
  }

#' Read CFM precomputed spectra from a database created by cfm_read_batch
#'
#' @param db_file [string] Full path to the database file
#' @param table_name [string] Name of table containing the CFM spectra to read
#' @param ID [string] A vector of ID(s) to retrieve from the database
#' @param return_annotation [logical] Should spectra be returned with annotations
#'
#' @return
#' @export
#'
cfm_read_db <-
  function(db_file = NULL,
           table_name = NULL,
           ID = NULL,
           return_annotation = F) {
    db_file <- normalizePath(db_file, mustWork = T)
    stopifnot(!is.null(table_name), !is.null(ID))
    conn <- DBI::dbConnect(RSQLite::SQLite(), db_file)
    on.exit(DBI::dbDisconnect(conn))
    stopifnot(table_name %in% DBI::dbListTables(conn))
    stopifnot(
      dplyr::tbl(conn, table_name) %>%
        dplyr::filter(ID %in% !!ID) %>%
        dplyr::count() %>%
        dplyr::pull() >= 1
    )

    if(is.null(ID)){
      a <- dplyr::tbl(conn, table_name) %>%
        dplyr::as_tibble()
    } else {
      a <- dplyr::tbl(conn, table_name) %>%
        dplyr::filter(ID %in% !!ID) %>%
        dplyr::as_tibble()
    }


    rlang::set_names(
      purrr::map(
        .x = a$spectrum,
        .f = cfm_parse_spec,
        return_annotation = return_annotation
      ),
      a$ID
    )
  }
